{% set name = "dftbplus" %}
{% set version = "22.1" %}

package:
  name: {{ name|lower }}-tools
  version: {{ version }}

source:
  url: https://github.com/aradi/dftbplus/archive/refs/heads/release-22.1.zip
  sha256: e737eefbf31463fd8a38679d70ac9399a7f141ac8ecf84229e40803eeb1bd222
  #url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  #sha256: e73aa698ff951b59f7fe2ea027b292bae16abf545c9fdbb11b5b5127f04a3c10

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install tools/dptools -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - numpy
    - dftbplus

test:
  imports:
    - dptools

about:
  home: https://{{ name }}.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING
    - COPYING.LESSER
  summary: 'DPTOOLS: Processing and converting data related to the DFTB+ package'
  doc_url: https://{{ name }}-recipes.readthedocs.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
