{% set name = "dftbplus" %}
{% set version = "25.1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}-tools
  version: {{ version }}

source:
  url: https://github.com/dftbplus/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 136088ffc8a3b27adca0cee46272966de62f2c42de91b632597fb12bf13c8d38

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install tools/dptools -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - dftbplus

test:
  requires:
    - python {{ python_min }}
  imports:
    - dptools

about:
  home: https://{{ name }}.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING
    - COPYING.LESSER
  summary: 'DPTOOLS: Processing and converting data related to the DFTB+ package'
  doc_url: https://{{ name }}-recipes.readthedocs.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
