{% set name = "dftbplus" %}
{% set version = "20.2" %}

package:
  name: {{ name|lower }}-tools
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6b1f10c7efbdaf59acf64d8fb8afc80460c0fbc6c4dbe256b760223cbd28ed2c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install tools/dptools -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - dftbplus

test:
  imports:
    - dptools

about:
  home: https://{{ name }}.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING
    - COPYING.LESSER
  summary: 'DPTOOLS: Processing and converting data related to the DFTB+ package'
  doc_url: https://{{ name }}-recipes.readthedocs.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
